using System;
using System.Collections.Generic;
using Silksong.ModMenu.Elements;

namespace Silksong.ModMenu.Generator;

/// <summary>
/// Marker interface for a menu generated by `[GeneratedModMenu]`.
/// </summary>
public interface ICustomMenu<T> : ICustomMenu
{
    /// <summary>
    /// Notified whenever any element within this group has its value changed.
    /// </summary>
    public event Action<CustomMenuValueChangedEvent>? OnValueChanged;

    /// <summary>
    /// Set all fields and properties on `data` to to match this entity's menu values.
    /// </summary>
    void ExportTo(T data);

    /// <summary>
    /// Set all this entity's menu values to match the fields and properties on `data`.
    /// </summary>
    void ApplyFrom(T data);

    /// <summary>
    /// Return all menu elements defined by this custom menu.
    /// </summary>
    IEnumerable<MenuElement> Elements();
}

/// <summary>
/// Parent marker interface without generics.
/// </summary>
public interface ICustomMenu { }
